openapi: 3.0.3
info:
  title: Tech4City Entry Coding Challenge - Cloud Control
  version: 1.0.0
servers:
  - url: "https://api.example.com"
    description: "placeholder"
  - url: "https://api.example.com"
    description: "placeholder 2"
paths:
  /results/{user_id}:
    get:
      summary: Get all results for user
      description: Populates the diary
      parameters:
        - name: user_id
          in: path
          description: ID of user whose results will be retrieved
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved user's results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Result"
        "400":
          description: Invalid ID / No results found
  /analyze:
    post:
      summary: Running inference with model
      requestBody:
        description: Image to be classified along with user ID
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              $ref: "#/components/schemas/AnalyzeRequest"
      responses:
        "200":
          description: Successful inference
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  image:
                    type: array
                    $ref: "#/components/schemas/Image"
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Result"
        "400":
          description: Error with payload or model
  /select:
    post:
      summary: Selecting correct classification
      requestBody:
        description: Result preferred by user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PreferredResult"
      responses:
        "200":
          description: Successful inference
        "400":
          description: Error

components:
  schemas:
    Image:
      type: object
      properties:
        image_id:
          type: integer
          format: int64
        user_id:
          type: string
        image_data:
          type: string
          format: binary
        upload_date:
          type: string
          format: date-time
    AnalyzeRequest:
      type: object
      properties:
        user_id:
          type: string
        image_data:
          type: string
          format: binary
        image_id:
          type: integer
          format: int64
    Result:
      type: object
      properties:
        result_id:
          type: integer
          format: int64
        user_id:
          type: str
        image_obj:
          $ref: "#/components/schemas/Image"
        label_name:
          type: string
        confidence_score:
          type: number
          format: float
        result_timestamp:
          type: string
          format: date-time
    PreferredResult:
      type: object
      properties:
        image_id:
          type: integer
          format: int64
        user_id:
          type: string
        result_id:
          type: integer
          format: int64
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format: int64
