openapi: 3.0.3
info:
  title: Tech4City Entry Coding Challenge - Cloud Control
  version: 1.0.0
servers: 
  - url: 'https://api.example.com'
    description: 'placeholder'
  - url: 'https://api.example.com'
    description: 'placeholder 2'
paths:
  /images:
    post:
      summary: Uploading an image
      requestBody: 
        description: Image to be classified
        required: true
        content: 
          application/octet-stream: {}
      responses:
        '200': 
          description: Successfully uploaded

  /images/{imageId}:
    get:
      summary: Get image by ID
      parameters:
        - name: imageId
          in: path
          description: Get image by ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '404':
          description: Image not found

  /infer:
    post:
      summary: Running inference with model
      requestBody: 
        description: Image to be classified
        required: true
        content: 
          application/octet-stream: {}
      responses:
        '200': 
          description: Successful inference
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Error with payload or model
components:
  schemas:
    Image:
      type: object
      properties:
        id: 
          type: integer
          format: int64
        filepath: 
          type: string
        upload_date: 
          type: string
          format: date-time
    Label:
      type: object
      properties:
        id: 
          type: integer
          format: int64
        label_name:
          type: string
    Result:
      type: object
      properties:
        result_id:
          type: integer
          format: int64
        image:
          $ref: '#/components/schemas/Image'
        label:
          $ref: '#/components/schemas/Label'
        confidence_score:
          type: number
          format: float

